### PR TITLE
Document the opts=optional attribute which can be used for an inclu…

### PR DESCRIPTION
**Pull request by jwillemsen**
…de directive and fixed one typo

### CODE REVIEW

**Comment by mojavelinux** [comment]
Awesome! Thanks!

It needs one correction before it can be merged. The optional option is specified using `opts=optional` (not `optional-option`). Could you update?

Also, would you be willing to add a sentence that explains that when the optional option is set, the processor will ignore the directive if the target cannot be found? (meaning no warning is shown).

**Comment by jwillemsen** [comment]
I will make an update tomorrow and test your proposed change, optional-option does seem to work

**Comment by mojavelinux** [comment]
> optional-option does seem to work

While I agree that's true, it's matching the internal name used to track the option, and thus should be avoided.

**Comment by mojavelinux** [comment]
Thanks!

**Pull request merged**
