### PR TITLE
resolves #993 redirect /docs/asciidoctor-revealjs to documentation site

### LINKED ISSUE #993: Redirect asciidoctor.org/docs/asciidoctor-revealjs to docs.asciidoctor.org/reveal.js-converter/
As the title says :wink:

### PR DESCRIPTION
**Pull request by Mogztter**
resolves #993

### CODE REVIEW

**Comment by mojavelinux** [comment]
Great job on the mapping. Thanks!

**Comment by mojavelinux** [comment]
Same for Asciidoctor.js, perhaps?

**Comment by Mogztter** [comment]
> Same for Asciidoctor.js, perhaps?

Good point!
Thankfully, there are only 4 sections titles on this page :grinning: 
For reference: https://asciidoctor.org/docs/asciidoctor.js/

**Comment by mojavelinux** [comment]
There were a lot more a while ago, but I can't see the value of redirecting those deep links now.

**Pull request merged**
