### PR TITLE
bump asciidoctor-maven-plugin version to 1.5.3

### PR DESCRIPTION
**Pull request by NicolasGeraud**

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks. I'm going to merge this just so that we can get the information fixed, but what really needs to happen is that the website needs to include the README from the code repository so that we don't have two separate documents with the same content. The reason I haven't done that yet is because the two documents have diverged and need to first be reconciled.

**Comment by NicolasGeraud** [comment]
Hi Dan,
They diverge from the way they organize content indeed, but the README looks more exhaustive.

**Comment by mojavelinux** [comment]
Yes, I should have clarified. The README is now the canonical source, but is missing a few bits of information from the version on asciidoctor.org. Unfortunately, the only way to fix it is a full scan to see what is missing from the README. As soon as we get that content moved over, we can just include the README and put this behind us.

**Comment by mojavelinux** [comment]
Btw, that's #612.

**Pull request merged**
