### PR TITLE
Add instructions on using an include with content on a list item (clo…

### LINKED ISSUE #876: Document adding content to a list item
As per http://discuss.asciidoctor.org/Includes-in-part-of-a-line-includes-in-numbered-lists-td7039.html#a7040

PR on the way.

### PR DESCRIPTION
**Pull request by danyill**
Closes #876

### CODE REVIEW

**Comment by mojavelinux** [comment]
@danyill I applied some revisions (okay, a lot). Let me know what you think.

It's important to distinguish the primary text of a list item from the complex content. I tried to do that in my edits.

**Comment by danyill** [comment]
LGTM. Thank you for taking the time to review. I felt uncomfortable using a word like a "trick" but couldn't think of a better way of expressing it. I think what you've written is clearer.

Out of curiosity, while are you fully qualifying the xref against the user manual (e.g. `<<user-manual.adoc##dropping-the-principal-text>>`) here?

**Comment by mojavelinux** [comment]
Thanks for reviewing, @danyill!

> Out of curiosity, while are you fully qualifying the xref against the user manual (e.g. <<user-manual.adoc##dropping-the-principal-text>>) here?

Technically, it's not necessary to make the reference work. But we're doing it that way so that it can be more easily migrated to Antora. Once we've made that switch, it will become the page ID you recognized.

**Comment by mojavelinux** [comment]
Btw, I also removed the other explicit IDs for the same reason. Once we're in Antora, everything will get reworked.

**Pull request merged**
