### PR TITLE
Nonenglish

### PR DESCRIPTION
**Pull request by rockyallen**

### CODE REVIEW

**Comment by rockyallen** [comment]
Sorry - I seem to have created a new pr when I was hoping it would update the previous one. Can you ignore the previous?

**Comment by mojavelinux** [comment]
Sure thing. Thanks for updating!

**Comment by mojavelinux** [comment]
I merged this as 8e3ffa873c4fc733c133ed853557e10ca7f79cad with some minor edits. I also renamed the file to *language-support.adoc* to keep the word English out of it as much as possible.

**Comment by mojavelinux** [comment]
Thanks again, @rockyallen! I'm really grateful that you added this section!

**Pull request closed without merging**
