### PR TITLE
Add anchor definition in list items

### PR DESCRIPTION
**Pull request by jmini**
Discussion on the Mailing List:
http://discuss.asciidoctor.org/anchor-link-to-ordered-list-item-td4256.html

### CODE REVIEW

**Comment by mojavelinux** [comment]
I like the proposal of adding a specific example (since specific examples always help bring clarity). However, I would also like to include a general description higher up that explains where anchors go in general. The description should say something like:

"In addition to being able to define anchors on sections and blocks, anchors can be defined inline where ever you can type normal text (anchors are a macro substitution). The anchors in the text get replaced with invisible anchor points in the output.

For example, you would not put an anchor in front of a list item:

```
[[anchor-point]]* list item text
```

Instead, you would put it at the very start of the text of the list item:

```
* [[anchor-point]]list item txt
```

Just keep in mind that inline anchor points are discovered where text is permitted. If text doesn't belong somewhere, then neither does an inline anchor point."

We might also want to explain the behavior of inline anchors in section titles, as they get slightly special treatment (and some caveats). But that may be for a separate issue.

**Comment by mojavelinux** [comment]
cc @jaredmorgs for review

**Comment by jaredmorgs** [comment]
Yeah, I like the idea of putting a more general description in as well.

@jmini would you feel comfortable amending your original PR and adding the extra info that @mojavelinux has suggested?

**Comment by jmini** [comment]
Yes of course. I did not had the time to do it.

**Comment by jaredmorgs** [comment]
No problem! Thanks for taking the time to do the PR.

On Mon, 8 Feb 2016, 17:35 Jérémie Bresson <notifications@github.com> wrote:

> Yes of course. I did not had the time to do it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/asciidoctor/asciidoctor.org/pull/489#issuecomment-181240232>
> .
>
-- 

Sent from Mobile.

**Comment by jmini** [comment]
I just pushed a new version of this patch.

I added an extra example of headers, derived from [this answer on StackOverflow](http://stackoverflow.com/a/35196109).

**Comment by mojavelinux** [comment]
Well done! Thanks for following up @jmini and thanks for the review @jaredmorgs. Teamwork!

**Comment by mojavelinux** [comment]
Did this close an issue? Just checking to make sure we didn't leave a dangling issue.

**Comment by jaredmorgs** [comment]
I'm not sure there was an issue open for this @mojavelinux .

**Comment by mojavelinux** [comment]
Great. Thanks for following up.

**Pull request merged**
