### PR TITLE
Refer to new release of asciidoctor-revealjs 1.1.0

### PR DESCRIPTION
**Pull request by obilodeau**
See https://github.com/asciidoctor/asciidoctor-reveal.js/releases/tag/v1.1.0

### CODE REVIEW

**Comment by Mogztter** [comment]
If you want to publish a blog post that would be awesome! http://asciidoctor.org/news/
The last post is more than a year ago 😬

**Comment by obilodeau** [comment]
What kind of blog post would the community be interested in?

Like intro to using AsciiDoc and reveal.js? Or talk about the highlights of ~~1.1.0~~ 1.1.1 (doctest, compiled slim transcompiled to JS with Opal, etc.) and what it means for the ecosystem and users?

I don't have much time to put into it but I can do a quick win if you are interested.

**Comment by mojavelinux** [comment]
The key with blog posts like these are to keep them concise and focus on a quick win. I would start of by saying, "so you want to create a reveal.js presentation, but you don't have a lot of time. We have just the toolset for you. You just create an AsciiDoc document, feed it to the asciidoctor-reveal.js converter, and out comes your presentation. here's how to do it." (then describe how to make a very basic presentation with a few slides)

I'd then move on to one nice enhancement they can get from it. Pick a feature, like source highlighting or vertical slides, and then tell them how to enhance the newly created presentation to take advantage of that feature.

Obviously, you'll need to pick either Ruby or JavaScript as the focus of this post. You could save the point about slim transpiled as JS w/ Opal for a follow-up post that's more technical).

**Comment by obilodeau** [comment]
Heads up. I started working on the blog post tonight.

**Pull request merged**
