### PR TITLE
Add section with Asciidoctor extensions

### PR DESCRIPTION
**Pull request by allati**
A followup to this [post](http://discuss.asciidoctor.org/MonoTree-extension-tp2903p2946.html) on asciidoctor forum. I doubt that this change can be considered "complete", but it's still something to start from.

I wasn't able to check if awestruct processes this change correctly - spent several hours trying to configure environment on Windows 7 (different combinations of ruby versions, build tools, etc.), but failed.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thanks for the pull request! Let me chat with @graphitefriction about the best way to organize this in the site. For sure, we'll get it in there!

**Comment by mojavelinux** [comment]
When we merge this, I think we should include a few more third-party extensions.

Name: Asciidoctor Screenshot
Description: Automate the inclusion of dynamically-generated screenshots into your documentation.
Runtime: AsciidoctorJ
URL: http://fix.github.io/asciidoctor-screenshot/

Name: Asciidoctor Gherkin
Description: Include Gherkin feature files in AsciiDoc in the form of sections, paragraphs, lists and tables.
Runtime: AsciidoctorJ
URL: https://github.com/domgold/asciidoctor-gherkin-extension

Name: Markup Document Builder
Description: This project is a document builder for markup documents, including AsciiDoc.
Runtime: AsciidoctorJ
URL: https://github.com/RobWin/markup-document-builder

**Comment by mojavelinux** [comment]
I like the idea of having a page to showcase extensions. I think that we should split the page into "official" extensions and "third-party" extensions. Official extensions are simply extensions that are inside the Asciidoctor organization on GitHub and managed as part of Asciidoctor. Third-party extensions are those that are developed outside of the Asciidoctor GitHub organization. It's always possible that an extension from the third-party list becomes an official extension (or vice-versa), so we don't want to make a big deal about the distinction. It's more about where to look.

**Comment by mojavelinux** [comment]
It's important to emphasize that "extensions" in this context are extensions to the AsciiDoc syntax or processor. This differs from extensions for other tools, like the Atom extension. The focus here is extensions in the context of the AsciiDoc content.

**Comment by mojavelinux** [comment]
Name: Asciidoctor Diagram
Description: A set of extensions for Asciidoctor that allow you to embed diagrams written using the PlantUML, Graphviz, ditaa, or Shaape syntax inside your AsciiDoc documents. 
Runtime: Asciidoctor
URL: https://github.com/asciidoctor/asciidoctor-diagram and/or http://asciidoctor.org/docs/asciidoctor-diagram/

Name: Asciidoctor LaTeX
Description: Asciidoc-LaTeX makes it possible to render documents written in AsciiDoc to LaTeX or HTML. It also defines an extended mathematical syntax for the AsciiDoc markup language that closely parallels LaTeX.
Runtime: Asciidoctor
URL: https://github.com/asciidoctor/asciidoctor-latex

The extension lab should be highlighted here as well. I would put it under "other" because it's more of a playground.

Name: Extension Lab
Description: A playground for new and experimental extensions. Used to test the capabilities of the extension mechanism.
Runtime: Asciidoctor
URL: https://github.com/asciidoctor/asciidoctor-extensions-lab

**Comment by mojavelinux** [comment]
Asciidoctor LaTeX has it's foot both in the extension world and the converter world, so I think it will end up showing up in both places (assuming we have a converters page or section in the future).

**Comment by mojavelinux** [comment]
The Markup Document Builder might end up being an infrastructure component rather than an extension.

**Comment by mojavelinux** [comment]
For the layout, ultimately we want something that looks more like a gallery (sort of like http://awestruct.org/gallery/ but more carefully structured).

**Comment by graphitefriction** [comment]
@mojavelinux I'm going to merge this now, as it is, since you've now added several in-depth comments to it that have spawned new content and issues that should be addressed on there own. I will reference this pull request though so that they all stay together.

@allati Thank you so much for getting the Extension documentation rolling! The document and changes you contributed work great!

**Pull request merged**
