### PR TITLE
Update Homebrew installation procedure for macOS

### PR DESCRIPTION
**Pull request by zmwangx**
Ref https://github.com/asciidoctor/asciidoctor/pull/2469.

I also removed/updated some heavily outdated information.

### CODE REVIEW

**Comment by mojavelinux** [comment]
Thank you! This is great!

Could you change "OS X" to "macOS" in the text? I know you had proposed that term originally and I had changed it. Now I realize I was the one who was getting it wrong.

I'll take care of renaming the file and updating the redirect file.

**Comment by zmwangx** [comment]
@mojavelinux Done. Also updated a few things about Xcode.

**Comment by mojavelinux** [comment]
Thank you @zmwangx. This is great!

**Comment by mojavelinux** [comment]
The redirects are now in place. See http://asciidoctor.org/docs/install-asciidoctor-macos

**Pull request merged**
