### PR TITLE
Resolves #521, move social links to footer

### LINKED ISSUE #521: Move social links to the footer
I think we should move "social" links to the footer:

footer

### PR DESCRIPTION
**Pull request by Mogztter**
Also replaced IRC by Gitter (as suggested by @mojavelinux)

Resolves #521

### CODE REVIEW

**Comment by mojavelinux** [comment]
Merged as f5eaa5dc071e257b398e95f2bed8a6bb0dc6ed8b with follow-up revisions made in a66f4086548350ad051cdefa53d0830b4a497b60.

Let me know how you like the new layout!

**Comment by mojavelinux** [comment]
In additional to some layout changes, I also did the following:

* switched to SVG badge (using shields.io)
* assigned a fixed width to icons by adding the fa-fw class

**Comment by Mogztter** [comment]
I like it :+1: 

We also need to update the index page to remove IRC and maybe use the badge for Gitter in the footer ?
 
index

**Comment by mojavelinux** [comment]
Keep in mind that any change to the index page right now is really a change to the Asciidoctor README.

I agree it's probably time to drop (or at least comment out) the IRC since most of us (none of us?) are there.

I think the Gitter badge in the footer would be overkill design-wise.

**Comment by mojavelinux** [comment]
Update made.

**Pull request closed without merging**
