### PR TITLE
Resolves #542 import from word (attempt 3)

### LINKED ISSUE #542: "Convert MS Word to AsciiDoc" content discussion
Use this issue as a tracker for content suggestions, or feel free to provide PRs referencing this ticket to keep track of contributions.

This content is contained in https://github.com/asciidoctor/asciidoctor.org/blob/master/docs/user-manual.adoc.

### PR DESCRIPTION
**Pull request by AlexanderZobkov**
This pull request includes the section (originally written by @rockyallen ) describing how to use pandoc to convert ms docx to asciidoc + fixes requested in #583 .
Let's finally have it as a part of the official documentation :smile:

### CODE REVIEW

**Comment by AlexanderZobkov** [comment]
Hello Dan,
Is the new section good for you or probably it requires additional corrections before merging into the officiall documentation?

**Comment by mojavelinux** [comment]
I decided to make this a dedicated guide since I think it's too specific for the general user manual. I did some cleaning up of the document and pushed it. We can handle revisions in separate issues.

Here's the result: http://asciidoctor.org/docs/migrating-from-msword

**Comment by mojavelinux** [comment]
Merged as 34332319eb1ca6d935f7347887a65f40b570c926.

**Comment by mojavelinux** [comment]
We're off to a good start!

**Pull request closed without merging**
