### PR TITLE
Add replacements subs for attributes tables

### PR DESCRIPTION
**Pull request by oncletom**
This way, `wj^[5]^` can be displayed as a footnote link.
At the moment, it is displayed as plain `wj^[5]^`.

### CODE REVIEW

**Comment by oncletom** [comment]
I'm unsure why it does not work though :-(

**Comment by das-g** [comment]
Maybe #794 is an alternative?

**Comment by mojavelinux** [comment]
> I'm unsure why it does not work though :-(

It doesn't work because the literal style was being applied to the cells and substitutions are not applied to literal table cells. @das-g gave me the idea of using a different style. In the end, I choose to apply the monospaced style in the first column and selectively the emphasis style in the second.

The problem is now fixed by a88280f83a3e517a45a2b158d2388c15a63639f9, though it still makes me wonder whether we need more control over substitutions on table cells.

**Comment by mojavelinux** [comment]
I forgot to close this issue as it is now resolved. Closing it now.

**Pull request closed without merging**
