### PR TITLE
Section Pending proposed content and bug approach

### PR DESCRIPTION
**Pull request by jaredmorgs**
This should give you an idea about what I propose for those sections that require more info. Let me know if you like this approach and I'll continue with this PR.

### CODE REVIEW

**Comment by jaredmorgs** [comment]
#432 relates to this PR.

**Comment by mojavelinux** [comment]
I like it! Great idea!

The change for Asciidoctor PDF got mixed up in this pull request. Could you remove that part of the change and force push?

Also, it's a good idea to always squash a pull request down to a single commit, if possible. That way, the history doesn't show local changes that weren't intended as part of the effective pull request.

**Comment by jaredmorgs** [comment]
I'm getting into better housekeeping for my PRs, so I'm closing this one off. I've created a PR that should be cleaner and more atomic, and will use the Amend function to push only one major change.

**Comment by mojavelinux** [comment]
:+1:

**Pull request closed without merging**
