### PR TITLE
Update extensions.adoc

### PR DESCRIPTION
**Pull request by sanyasandor**
extended with HTML Image Map block processor

### CODE REVIEW

**Comment by mojavelinux** [comment]
Can you provide a syntax example in the README of the project that shows how this extension is used in an AsciiDoc document?

**Comment by sanyasandor** [comment]
README is now updated. Also attached a generated html next to the example.adoc

**Comment by mojavelinux** [comment]
Thanks. Though when I said README, I was actually talking about the description on this page: https://launchpad.net/imagemap-block-processor I missed that there was a README in the repository.

> Also attached a generated html next to the example.adoc

That seems unnecessary. Generally you shouldn't commit generated files.

When I looked at the README, I noticed this:

```
==  ImageMap example
:doctype: html
```

That's not valid. The doctitle should only have single `=`, and html is not a valid doctype. It should be:

```
=  ImageMap example
```

As for merging this, I would prefer to add it to this list here: https://github.com/asciidoctor/asciidoctor-extensions-lab#other-extensions There are things about this extension that I consider to be unorthodox and I don't want to promote it (at least not yet) as a community extension. The lab is really where this reference belongs for now.

**Comment by sanyasandor** [comment]
Thanks for the hint. I updated that introduction page on Launchpad as well
and removed the :doctype: from all examples, also the generated file is
gone. My goal was to share this, was not sure about the proper place. This
one seemed practical with a simple link to the repository.

How shall I proceed with the extensions-lab ? Shall I make a pull request
there initially, and whenever an update is coming ?

Dan Allen ***@***.***> ezt írta (időpont: 2023. dec. 7., Cs,
20:56):

**Comment by mojavelinux** [comment]
I can take care of adding it there. No need to worry. You've provided all the information I need. Thanks!

**Comment by sanyasandor** [comment]
Great ! thanks ! :-)

Dan Allen ***@***.***> ezt írta (időpont: 2023. dec. 7., Cs,
21:42):

**Pull request closed without merging**
